### ISSUE TITLE
No licence specified for this project

### ISSUE THREAD

**Issue by jviaches** [fazzdev/Team-Dashboard#1]
This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

Might be i could not find one ?

**Comment by fazzdev** [comment]
Good point. I am new in this license thing. The library that I am using is under 'Microsoft Public License (Ms-PL)'. Do you think I can use MIT License for this project?

**Comment by jviaches** [comment]
It's new to me as well but I think MIT might be a great choice for this project :)
